### ISSUE TITLE
Generate action name constants in generated partial controllers

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#12]
We need to generate the action name constants in our generated partial controller classes.

**Comment by wwwlicious** [comment]
Currently I've added all public methods from a controller class in my fork, not sure if it should only be those with return types containing IActionResult though, either directly or as part of generic typeparameters

**Comment by kevinkuszyk** [comment]
We'll need to check how this works with methods which return other types, e.g. `IEnumerable<FooModel>`, now that WebAPI is integrated with MVC.

We should also exclude methods with the `[NonAction]` action attribute on them.

**Comment by wwwlicious** [comment]
Nonaction seems like a definite.

The tricky part with trying to filter controller methods is that with Mvc I could return simple types like strings, ints, bools and collections of them, it could also return void. 

Currently it will pick up [all public ordinary methods](https://github.com/wwwlicious/R4MVC/blob/dev/src/R4Mvc/SyntaxHelpers.cs#L104) (this excludes ctor/dtor's)

I think there is some danger in trying to filter out methods (except for nonaction and r4mvcexclude) as the criteria does not seem easy to define. It might be an area where a convention will do and an override provided by way of options or delegates might offer the best flexibility.

**Comment by kevinkuszyk** [comment]
Sorry - I misread your earlier comment - I thought you said you only include methods which return `IActionResult`.

I think all public methods, except those decorated with `[NonAction]` or `[R4MvcExclude]` is what we should go for.

**Comment by artiomchi** [comment]
I'm wondering if this is still necessary or not.

The reason the action name constants were added in the first place (based on my research) is to be able to reference the actions in Attributes. Since this project is for ASP.NET Core, it's a given that it will be compiled with a C# 6 or newer compiler, which adds `nameof()` expressions.

So instead of having an attribute that references an action like this:
```csharp
HomeController.ActionNameConstants.Index
```
it can now be referenced as follows (not using T4MVC entirely)
```csharp
nameof(HomeController.Index)
```

In C# this will be a constant which makes it identical to the previous expression, it gets compile time validation, and in a way more readable/superior, making the existing constants class obsolete.

As such, I suggest we remove the Action name constants class.

Thoughs?

**Comment by kevinkuszyk** [comment]
It might be useful to keep this to maintain API surface compatibility with T4MVC.

Having said that, I don't think it's a high priority, so I'll move it to the backlog.

**Comment by artiomchi** [comment]
One thing to note about this is we should probably decide on this before the first release.

The code is already in place to generate it, and it doesn't take much space. It was more of a question of what's correct and how can we enforce good practices / get people to use modern APIs. 

Once the first stable build is released, removing features will be more troublesome / bad compared to not adding them in the first place :)
