### ISSUE TITLE
Support areas

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#14]
We need to add support for MVC areas.

**Comment by wwwlicious** [comment]
Areas can be defined in controller attributes which we should be able to get from the controller nodes returned from the rewriter.

They can also be registered in the routetable directly. Do we need to pick these up? 
Will need to review the mvc code as I'm not as familiar with the internal population of areas into the routedictionary. 

Have you any thoughts on this one?

**Comment by kevinkuszyk** [comment]
I never use areas, but they are in the framework so we should support them.

> Areas can be defined in controller attributes which we should be able to get from the controller nodes returned from the rewriter.

> They can also be registered in the routetable directly. Do we need to pick these up? 
Will need to review the mvc code as I'm not as familiar with the internal population of areas into the routedictionary.

I'll have a look at T4MVC code to see what's done there.  I would suggest doing something similar in R4MVC.

**Comment by artiomchi** [comment]
So areas have changed in MVC Core. Compared to ASP.NET MVC, where you had an Area Registration class, and needed a specific folder structure, controllers in MVC Core can be in ANY folder, and as long as they have an Area attribute - they'll be part of that area.

That part was simple enough to handle. A somewhat more complicated scenario occurs when you want to move away from Magic strings. In my project, I've created an attribute per area, so that the area name is only present in a single place. I've added basic code to handle derived area attributes, but I'll revisit it later to see if I can make the code prettier.

This is working in af9c9b0, and will be in the next pull request

**Comment by artiomchi** [comment]
@wwwlicious 

> They can also be registered in the routetable directly.

I couldn't find any reference to this anywhere.. To be honest, I don't even remember that being in earlier versions of MVC Core.. Unless I'm mistaken- that's not something we have to worry about
