### ISSUE TITLE
SPIKE: How to do dependency injection?

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#2]
We need figure out how to do DI in R4MVC.  

I think we can hook into the framework's DI container using the`IServiceProvider`.  Questions:
1. Is this possible and how to do it?
2. How / where do we register our dependencies?

**Comment by wwwlicious** [comment]
I hadn't thought about using DI much yet, did you have anything specific in mind for this?

**Comment by kevinkuszyk** [comment]
Only that there is a new [dependency injection library](https://github.com/aspnet/DependencyInjection) and we should probably use that.

We'll need to decouple the code so it can be unit tested.  I'll try to flash out mockup this week of how I envisaged the services looking.  I'll be interested in your thoughts once I have something to share.

**Comment by artiomchi** [comment]
You're absolutely right on this one.

I can see that the services are already registered in [IocConfig.cs](https://github.com/T4MVC/R4MVC/blob/master/src/R4Mvc/Ioc/IocConfig.cs). I've changed the method to receive a IServiceProvider as a parameter, and have a void return.

A new `ServiceCollection` is initialised in `Program.cs`, then the services are registered in `IocConfig`. Finally, the service provider is built, which can be used to initialise services, specifically the `R4MvcGenerator` class.

Before the final release, most things will be initialised using the service provider instead of direct initialisation.
