### ISSUE TITLE
Load array settings from r4mvc.json config file

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#37]
To finish the work started in PR #35.

The following settings will be expressed as arrays:
1. `StaticFilesFolders`
2. `ExcludedStaticFileExtensions`
3. `ExcludedViewExtensions`

When the configuration sub system supports arrays we can add these to the `r4mvc.json` file.

**Comment by artiomchi** [comment]
Since the project is already using .Microsoft's DI library, I thought to also use their Configuration library as well. It can manage multiple configuration sources (currently json + command line params for overrides, + deffault values). It works perfectly well with handling arrays as well without the need for any extra code or complexity! So that's probably done once b13b8d6b is merged

**Comment by kevinkuszyk** [comment]
@artiomchi thanks.  Back in the early days the config system didn't support arrays, but they have 1st class support now.

I'll leave this open for now.  When you open that PR, can you make a note that it should close this issue?

**Comment by artiomchi** [comment]
Of course. It'll close/progress a number of issues in fact

**Comment by kevinkuszyk** [comment]
@artiomchi was this included in PR #47?

**Comment by artiomchi** [comment]
Oh, whoops. I missed this issue. Yes, this can be closed now
