### ISSUE TITLE
Make existing controllers into partial classes

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#6]
We need to make existing controllers into `partial`classes and make all the action methods `virtual`.

**Comment by wwwlicious** [comment]
For modifying existing partial classes I used a ControllerRewriter with an override for VisitClassDeclaration

The classes are marked as partial [here](https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/ControllerRewriter.cs#L41)

Currently I rely on the semantic model to get the declaring type which in turn I use to determine if the class is an MVC controller class. 

An issue with this is that once you update the node, it invalides the CompilationUnit in the syntax tree and my override for VisitMemberDeclaration will not be able to get the semantic model for the member (which again I use to determine if this is an MVC Controller member)

I am investigating how to avoid using the semantic model for type resolution but this appears pretty difficult vs creating a new compilation unit for the syntaxnode passed to the VisitMemberDeclaration override

**Comment by artiomchi** [comment]
I think this can be closed as well, pending @wwwlicious's confirmation. If I understand his comment here there was an issue with changing classes during the compilation process, since back then the code was executing in the early stages of the compilation process. The way the module is currently running - that doesn't seem to be a problem, and there's no reference to `VisitMemberDeclaration` in the project anymore.

At the same time, the controllers are marked as partial without any issues.

**Comment by kevinkuszyk** [comment]
Sounds fine to me.  @wwwlicious?

**Comment by wwwlicious** [comment]
@artiomchi @kevinkuszyk Yes, I agree this can be closed
