### ISSUE TITLE
MSBuild failure

### ISSUE THREAD

**Issue by JasonXtreme** [T4MVC/R4MVC#82]
Running Generate-r4mvc produces the following error:

Failure: Msbuild failed when processing the file '<path_to_project>.csproj' with message: Invalid static method invocation syntax: "[MSBuild]::IsRunningFromVisualStudio()". Method '[MSBuild]::IsRunningFromVisualStudio' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

This is project a few months of age that went untouched for about a month. Judging from the existing code, the code generator was working in the past (generated static classes exist).

**Comment by kevinkuszyk** [comment]
Thanks for your contribution.  We welcome pull requests if you would like to submit a fix.

**Comment by JasonXtreme** [comment]
If I manage to get into it and actually find a fix, I'll be sure to let you know.

**Comment by artiomchi** [comment]
Hmm, interesting.. I've just replicated this on my environment, after updating to the latest VS. Seems like they made some changes in the latest MSBuild version. There was an issue in the past regarding identifying the version of VS, so we had to add a workaround for this. It sounds like it should no longer be necessary

I'll get a patch for this asap. 

Sorry for the delay, seems like I haven't been receiving any notifications for new issues from GitHub. @kevinkuszyk is there any way to update the project so that I get notifications for new issues as well, please?
