### ISSUE TITLE
msbuild support

### ISSUE THREAD

**Issue by cortex93** [T4MVC/R4MVC#86]
Hi,

Would be a great addition to support msbuild. The idea will be to add a build/.targets file to the package so that files are generated at build and ensure consistency in CI scenario.

Regards

**Comment by cortex93** [comment]
Adding in csproj
`  <Target Name="GenerateR4MVC" BeforeTargets="CoreCompile">
    <Exec Command="dotnet r4mvc" />
  </Target>`

ends in infinite loop.

**Comment by artiomchi** [comment]
Hmm, definitely an interesting feature.

The reason it doesn't work yet is because the `dotnet` command isn't finished yet, so it can only be triggered using PowerShell, and the PS module has to be imported from the nuget package path.

I'll keep this open until I have the dotnet cli working, at which point we can test it again

**Comment by artiomchi** [comment]
Waiting for #64

**Comment by artiomchi** [comment]
The CLI tool just recently went live, so this is now possible.

If the cli tool is installed globally, it's as simple as this:
```xml
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="r4mvc generate" />
  </Target>
```

If the tool is installed locally, you'll have to add the tool path, of course.
