### ISSUE TITLE
Razor pages support

### ISSUE THREAD

**Issue by dealdiane** [T4MVC/R4MVC#97]
I know it's probably very new and not a lot of people are aware of it at the moment but it would be nice to start considering this now since it will ship with the next version (2.1) of aspnetcore.

**Comment by kevinkuszyk** [comment]
Thanks for the suggestion.  I haven't used Razor pages, so I'm not sure how this would work.  If you could post some use cases here, that would be useful.

We also welcome contributions if you'd like to open at PR which adds this!

**Comment by artiomchi** [comment]
@dealdiane Actualy, Razor Pages have been live for quite a while, from the initial release of aspnetcore 2.0!

There's a couple reasons why they're not in R4Mvc yet. Mainly they're not used as extensively as MVC controllers, and the project started as a T4MVC migration. So the Pages support was lower on the priority list.

Razor Pages have their own routing system as well, which is different to the standard MVC Controllers one, so that would require some work in getting familiarised with the inner workings of it, and making it work in a... R4Mvc way.

I'll add this link here as well for further info about Razor Pages (this is the 2.0 version, the features added in 2.1 wouldn't affect us much): https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.0

**Comment by artiomchi** [comment]
So far I've been using in (in somewhat simple scenarios, admittedly) since it went live, and it's been working quite well!

I've just added two small bugfixes, but unless there are any issues or anything missing, I believe this is OK now
